name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install backend deps and test
      working-directory: backend
      run: |
        npm install
        npm test

    - name: Install frontend deps and test
      working-directory: frontend
      run: |
        npm install
        npm test

        
