name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      #######################
      # 🔧 Backend Setup
      #######################
      - name: Clean install backend dependencies
        working-directory: backend
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install

      - name: Ensure Jest is executable in backend
        working-directory: backend
        run: chmod +x node_modules/.bin/jest

      - name: Run backend tests
        working-directory: backend
        run: npm test

      #######################
      # 🌐 Frontend Setup
      #######################
      - name: Clean install frontend dependencies
        working-directory: frontend
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install

      - name: Run frontend tests
        working-directory: frontend
        run: npm test




        